######################################################################
# Automatically generated by qmake (3.0) dt. maig 24 19:25:22 2016
######################################################################

TEMPLATE = app
TARGET = hash
INCLUDEPATH += .

# Input
HEADERS += dialog.h dialog2.h mainwindow.h
FORMS += dialog.ui dialog2.ui mainwindow.ui
SOURCES += dialog.cpp dialog2.cpp main.cpp mainwindow.cpp
